// Generated by CoffeeScript 1.10.0
app.directive('ngFileModel', function() {
  return {
    scope: {
      'ngFileModel': '='
    },
    link: function(scope, el, attrs) {
      return el.bind('change', function(changeEvent) {
        var reader;
        reader = new FileReader();
        reader.onload = function(loadEvent) {
          return scope.$apply(function() {
            return scope.ngFileModel = {
              name: changeEvent.target.files[0].name,
              data: loadEvent.target.result
            };
          });
        };
        console.debug(JSON.stringify(scope.ngFileModel));
        return reader.readAsDataURL(changeEvent.target.files[0]);
      });
    }
  };
});

app.directive('pwcheck', function() {
  return {
    restrict: 'A',
    require: 'ngModel',
    link: function(scope, el, attrs, ngModel) {
      return ngModel.$validators.pwcheck = function(modelValue) {
        return scope.inboxCtrl.checkPassword();
      };
    }
  };
});
